sudo: false

git:
  depth: 10

branches:
  only:
    - master
    - next

language: node_js

cache:
  directories:
    - $HOME/.npm
    - node_modules

matrix:
  include:
    - node_js: "10"
      script: npm run pretest
      env: CI=pretest
    - node_js: "10"
      script: npm run test:only
      env: CI=tests 10
    - node_js: "12"
      script: npm run test:only
      env: CI=tests 12
    - node_js: "13"
      script: npm run test:only
      env: CI=tests 13

before_install:
  - npm install -g npm@latest

install:
  - npm ci

before_script:
  - node --version
  - npm --version
